language: go

go:
- '1.11'
- '1.12'
- '1.13'

env:
- GO111MODULE=on GOLANGCI_LINT_VERSION=1.21.0

install:
- wget -q https://github.com/golangci/golangci-lint/releases/download/v$GOLANGCI_LINT_VERSION/golangci-lint-$GOLANGCI_LINT_VERSION-linux-amd64.tar.gz -O /tmp/golangci-lint.tar.gz
- tar --strip-components=1 -C $GOPATH/bin -xzf /tmp/golangci-lint.tar.gz
- go get github.com/mattn/goveralls

script:
- golangci-lint run --config .golangci.yml ./...
- go test -mod=readonly -v -race -count=1 -cover -coverprofile=profile.cov ./...

after_success:
- goveralls -coverprofile=profile.cov -service=travis-ci
